### ISSUE TITLE
Jobs with R0 (timesToRepeat: 0) get re-run upon server restart 

### ISSUE THREAD

**Issue by james-m** [ajvb/kala#105]
Hello,

What I'm seeing is something that doesn't quite square with my understanding of how things should be (and my understanding may be off here). If a job is submitted with R0--that is only to execute a single time and not scheduled to repeat--and then I restart the kala process, it reads the jobs back in from the job cache with a start time in the past and then executes the job. 

I ran a test case with a job that curls a locally running web server, and when restarting kala I see an entry in the web servers log indicating it was hit. Furthermore, the stats for the job when inspected by GET on /job/{job_id} indicates the job executing a few times (see attached job JSON) even though it is meant to only execute once.

Is this expected behavior? I'm a misconfiguring somehing, or is it a bug?

Thanks much.

Here's the JSON for the job. This was supposed to execute once, but I restarted the server twice after it executed once, resulting in multiple executions:
```json
{
    "job": {
        "command": "curl http://localhost:8080",
        "dependent_jobs": null,
        "disabled": false,
        "epsilon": "",
        "id": "89e33016-9240-43b2-6516-89b26f96bac6",
        "metadata": {
            "error_count": 0,
            "last_attempted_run": "2016-03-01T00:17:19.920306138Z",
            "last_error": "0001-01-01T00:00:00Z",
            "last_success": "2016-03-01T00:17:19.933363004Z",
            "success_count": 3
        },
        "name": "scheduled job",
        "next_run_at": "2016-03-01T00:08:13.10126407Z",
        "owner": "",
        "parent_jobs": null,
        "retries": 0,
        "schedule": "R0/2016-02-29T16:07:58-08:00/PT",
        "stats": [
            {
                "execution_duration": 18041450,
                "job_id": "89e33016-9240-43b2-6516-89b26f96bac6",
                "number_of_retries": 0,
                "ran_at": "2016-03-01T00:07:58.001177058Z",
                "success": true
            },
            {
                "execution_duration": 15145524,
                "job_id": "89e33016-9240-43b2-6516-89b26f96bac6",
                "number_of_retries": 0,
                "ran_at": "2016-03-01T00:08:13.101358483Z",
                "success": true
            },
            {
                "execution_duration": 12510431,
                "job_id": "89e33016-9240-43b2-6516-89b26f96bac6",
                "number_of_retries": 0,
                "ran_at": "2016-03-01T00:17:19.920854808Z",
                "success": true
            }
        ]
    }
```

**Comment by ajvb** [comment]
Hey @james-m, sorry for the delayed response.

So that is absolutely not expected behavior. I have a quick fix in testing at the moment, and will merge it into master shortly.
