### ISSUE TITLE
Error deleting jobs when using Redis

### ISSUE THREAD

**Issue by benwaine** [ajvb/kala#110]
It is not possible to delete a job when using Redis as the JOB DB. 

Steps To Reproduce: 

1) Start Kala using Redis as job DB

```
go run main.go run --jobDB=redis --jobDBAddress=127.0.0.1:6379
```

2) Schedule a job in kala

```bash
curl http://127.0.0.1:8000/api/v1/job/ -d '{"epsilon": "PT5S", "command": "bash /home/ajvb/gocode/src/github.com/ajvb/kala/examples/example-kala-commands/example-command.sh", "name": "test_job", "schedule": "R2/2017-06-04T19:25:16.828696-07:00/PT10S"}'
{"id":"846214c9-e739-4068-7e5a-f1fd58774884"}
```

3) Delete the newly scheduled job 

```bash
curl localhost:8000/api/v1/job/846214c9-e739-4068-7e5a-f1fd58774884/ -X DELETE
```

**Note:** error in log, job still present in Redis

```
ERRO[0054] Error occured while trying to delete job from db: ERR wrong number of arguments for 'hdel' command
```

4) Query job list or job individually 

```
curl http://127.0.0.1:8000/api/v1/job/
```

**Note** error in log, no job returned

```
ERRO[0000] Error occured when trying to get the job you requested.
```

5) Restart kala

6) Query job list of job individually, **note** the job has returned

Fix: Add missing argument to Redis `hdel` command.  Supplied in PR: https://github.com/ajvb/kala/pull/109

**Comment by ajvb** [comment]
Fixed by #109 - Thank you for this!
