### ISSUE TITLE
A job can be executed more that it's R value when kala is restarted (redis)

### ISSUE THREAD

**Issue by benwaine** [ajvb/kala#114]
A job's `timesToRepeat` value is used to determine when a job is scheduled. 

```go
func (j *Job) Run(cache JobCache) {
	// Schedule next run
	j.lock.RLock()
	jobRunner := &JobRunner{job: j, meta: j.Metadata}
	j.lock.RUnlock()
	newStat, newMeta, err := jobRunner.Run(cache)
	if err != nil {
		log.Errorf("Error running job: %s", err)
	}

	j.lock.Lock()
	j.Metadata = newMeta
	if newStat != nil {
		j.Stats = append(j.Stats, newStat)
	}
	if j.timesToRepeat != 0 {
		j.timesToRepeat--
		go j.StartWaiting(cache)
	}
	j.lock.Unlock()
}
```

However the `timesToRepeat` value may not be written to Redis (when using the gob encoder - not sure if private properties are encoded) and is definitley overridden when retrieving the job from storage. 

`redis/DB.GetAll()` is called when populating the cache when Kala is booted. **Note: InitDelayDuration re-parses the schedule sting and overwrites j.timesToRun**

```go
func (d DB) GetAll() ([]*job.Job, error) {
	jobs := []*job.Job{}

	vals, err := d.conn.Do("HVALS", HashKey)
	if err != nil {
		return jobs, err
	}

	for _, val := range vals.([]interface{}) {
		j, err := job.NewFromBytes(val.([]byte))
		if err != nil {
			return nil, err
		}

		err = j.InitDelayDuration(false)
		if err != nil {
			return nil, err
		}

		jobs = append(jobs, j)
	}

	return jobs, nil
}
```

I'm working on a fix and will PR it shortly.

**Comment by ajvb** [comment]
@benwaine If https://github.com/ajvb/kala/pull/115 properly fixed this, will you close this issue?

**Comment by benwaine** [comment]
Thanks, I'll build master today and take a look.

**Comment by ajvb** [comment]
@benwaine Can we close this?
