### ISSUE TITLE
Add --persist-every command line option

### ISSUE THREAD

**Issue by ajvb** [ajvb/kala#131]
Main idea is that persisting can at times be expensive, and every 5 seconds may be too frequent. Allow users to set there own while retaining the default of every 5 seconds.

`--persist-every` would set the `persistWaitTime` argument here: https://github.com/ajvb/kala/blob/master/job/cache.go#L69 which is passed in here https://github.com/ajvb/kala/blob/master/main.go#L150.

Per @jrxFive's comment here: https://github.com/ajvb/kala/pull/130#issuecomment-255533627

**Comment by leonardogcsoares** [comment]
I'm up for this! =D Claim!

**Comment by leonardogcsoares** [comment]
PR at #133! Cheers! =D

**Comment by ajvb** [comment]
Fixed with #133
