### ISSUE TITLE
Job output should be able to be saved to db if requested

### ISSUE THREAD

**Issue by levrado** [ajvb/kala#138]
I think a nice feature would be adding an optional field to new job request that will save the output of the command in the db, that can be accessed later by `/api/v1/job/<id>/output`

what do you feel about that?

**Comment by ajvb** [comment]
I like this concept. I think having a boolean field on `Job` called something list `PersistOutput` would be great.

**Comment by wuranxu** [comment]
Hi~
I'd like to get the output of command, what should I do ?
I have tried to make a request "post /api/v1/job/start/{id}" but there is not any response, waiting for your reply, thanks a lot.
