### ISSUE TITLE
Recurring job scheduling

### ISSUE THREAD

**Issue by desilvaNSP** [ajvb/kala#142]
Can we do recurring job scheduling by using these apis.

[Recurring Report Scheduler](https://technet.microsoft.com/en-us/library/cc984434.aspx)

Basically I want to create dynamic report scheduler. I want to create some service time cronjob to run specific script.

**Comment by ajvb** [comment]
I'm confused, are you trying to connect Kala to some Microsoft thing or trying to figure out how to do what you want with the ISO 8601 syntax?

**Comment by desilvaNSP** [comment]
Yeah, I have studied that syntax.and I solved my problem thank you @ajvb
