### ISSUE TITLE
How to scheule Daily job  Monday to Friday

### ISSUE THREAD

**Issue by desilvaNSP** [ajvb/kala#144]
I have issue with how to defined schedule to execute job only Monday to Friday in weekdays.It should be excecute every monday to friday in each week without creating multiple jobs.

**Comment by ajvb** [comment]
The ISO8601 has no conception of "Day of the Week" - https://github.com/ajvb/kala#interval-between-runs

Instead, what I would suggest is that in the script you run with Kala you have some logic to not run on Saturday or Sunday.
