### ISSUE TITLE
NextRunAt - reports latest time not earliest

### ISSUE THREAD

**Issue by shunte88** [ajvb/kala#146]
the logic for determining next run time for a set of jobs is reversed and thus reports the latest run at time for the set

		if nextRun.IsZero() {
			nextRun = jobs.NextRunAt
		//} else if (nextRun.UnixNano() - jobs.NextRunAt.UnixNano()) < 0 {
		} else if (nextRun.UnixNano() - jobs.NextRunAt.UnixNano()) > 0 {
			nextRun = jobs.NextRunAt // we want earliest not latest
		}

simple fix to reverse the test ( > 0)

**Comment by sblcook** [comment]
Is it just the one line that needs to be changed?

**Comment by shunte88** [comment]
yep just that one line

**Comment by sblcook** [comment]
Sweet. I will trying forking it and fixing it
