### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by giorgiootto** [ajvb/kala#151]
Hi,
How is status this project???

**Comment by ajvb** [comment]
Hey @giorgiootto,

It's semi-dead. I will put in time when I have it, but I haven't had much time recently.

**Comment by gwoo** [comment]
@ajvb Is there place we could move it and open it up to more maintainers?

**Comment by ajvb** [comment]
@gwoo I'd be happy to you and anyone who shows interest as maintainers. Are you interested?

Also, if desired, we could migrate this repo to an organization. Not sure if that would allow us anything beyond keeping it here, but happy to do so.

**Comment by gwoo** [comment]
@ajvb I am interested in maintaining the project. I could add you to [go-big organization](https://github.com/orgs/go-big/) Not many of us there yet, but working on it.

**Comment by ajvb** [comment]
@gwoo Added you as a collaborator.

In regards to the `go-big` organization, lets hold off on migrating there for now but I'm open to discussing it.

Let me know if you need anything in regards to maintaining `kala`.

**Comment by gwoo** [comment]
@ajvb Cool!

First act as maintainer is closing this thread.
