### ISSUE TITLE
Disable/enable a Job

### ISSUE THREAD

**Issue by dzakaammar** [ajvb/kala#184]
I see that a Job struct has a disable status. What do you do to change the disable status after job creation? Regards.

**Comment by ajvb** [comment]
Haha, never realized these endpoints were not documented! Sorry about that @dzakaammar 

[As you can see here](https://github.com/ajvb/kala/blob/master/api/api.go#L314-L317), all you have to do is sent a POST request to either: `/api/v1/job/disable/{id}` or `/api/v1/job/enable/{id}` where `{id}` is the Job ID of the Job you want to disable or enable. That will disable or enable that job.

**Comment by dzakaammar** [comment]
Haha, no problem. Big thanks!
