### ISSUE TITLE
Cluster support?

### ISSUE THREAD

**Issue by dangkaka** [ajvb/kala#186]
Hi,

Does `kala` support to run in cluster?
I see kala run "worker" and http server in same process and I don’t see where you solve race condition issue in worker
If only 1 server can be up => we can't make sure service available.

Good library overall !!

**Comment by ajvb** [comment]
Hey @dangkaka,

No it doesn't and it almost certainly never will. There is a [short snippet in the README](https://github.com/ajvb/kala#i-need-fault-tolerance-distributed-features-this-to-work-at-scale) about this.

A design goal of Kala is to keep it very simple. Single host, no external services required (default is BoltDB for persistence).

**Comment by dangkaka** [comment]
okk, thanks
