### ISSUE TITLE
Does it still in alpha?

### ISSUE THREAD

**Issue by batizhevsky** [ajvb/kala#188]
>#### Currently in Alpha stage. Do not use in production environments.
It has been 3 years since this was committed. Is this project still not ready for production?

**Comment by tooolbox** [comment]
> **Currently in Alpha stage. Do not use in production environments.**

It has been 4 years since this was committed.  Is this project still not ready for production?

🙂

**Comment by tooolbox** [comment]
No known facts contradict that statement in the README.

If anyone has used this in production or even in a very long duration without incident, we can remove the statement.
