### ISSUE TITLE
Support RabbitMQ/Redis for publishing event

### ISSUE THREAD

**Issue by iEAmi** [ajvb/kala#210]
Is this a good idea to add rabbitMQ (AMQP) support for remote command?
of course, publishing into rabbitMQ can be achieved using HTTP

**Comment by tooolbox** [comment]
My personal preference would be to use HTTP for this.

Currently the two supported jobs are "run a shell locally" and "use HTTP to run something remotely".  These two job types cover almost every conceivable use case, and I don't think we want to start adding more job types unless we find there's something that absolutely can't be accomplished given the two that exist.

Hope that makes sense?

**Comment by iEAmi** [comment]
This makes sense.
Shell and HTTP cover most use cases.
