### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by little-joe999** [ajvb/kala#234]
Not sure if I did something wrong, once I cloned the repository and ran the installer (locally or the build command for Docker) I am ending up in getting a '404 page not found' error when connecting to localhost:8000.
Any advice?

**Comment by ajvb** [comment]
You're going to want to view `localhost:8000/webui/` for the web ui.

**Comment by tooolbox** [comment]
@little-joe999 since it seems like your issue is resolved I'm going to close this, but please reopen it if I'm mistaken.

**Comment by little-joe999** [comment]
Oh yeah, sorry forgot to reply. The link you've provided solved the issue. Thanks a lot.
