### ISSUE TITLE
Deleted job is still running

### ISSUE THREAD

**Issue by 1602** [ajvb/kala#237]
I created a job running every minute, then I deleted it, now stats endpoint and UI show that I don't have jobs, but I still see requests coming every minute (this is a remote jobs triggering POST to an API endpoint). Is there a way to delete the job and make it stop running?

**Comment by n10ty** [comment]
Having the same issue. Deleted jobs are still running

**Comment by josejuanmontiel** [comment]
Same here and validate that PR of @n10ty fix it

**Comment by tooolbox** [comment]
Thanks, I have a question on the PR from @n10ty but otherwise I get it, this should be handled.  (!)

**Comment by tooolbox** [comment]
Closed by #257
