### ISSUE TITLE
--bolt-path does nothing

### ISSUE THREAD

**Issue by 1oglop1** [ajvb/kala#251]
Hi, I tried to use kala with BoltDB inside the docker container and wanted to use the parameter `--bolt-path` to specify the file location, however it does not seem to do anything and kala still creates `jobdb.db` file in the same directory as `kala` executable.

```
kala serve --jobdb=boltdb --bolt-path=/kala/data/kala.db
```

Could you confirm this is the case or am I doing something wrong?
Thank you!

**Comment by zhangrr** [comment]
Modify cmd/server.go

switch viper.GetString("jobdb") {
		case "boltdb":
			db = boltdb.GetBoltDB(viper.GetString("boltpath"))

Change to 
                        db = boltdb.GetBoltDB(viper.GetString("bolt-path"))

Run it :
./kala serve --jobdb=boltdb --bolt-path=/data/db

**Comment by 1oglop1** [comment]
Ah thanks for the workaround, I was looking at this piece of code but not knowing enough about used frameworks it did not strike me that there is a typo!
