### ISSUE TITLE
Use strings.HasSuffix instead of strings.HasPrefix in client/client.go/New()

### ISSUE THREAD

**Issue by FrankRuben** [ajvb/kala#34]
Hi,
I think in client/client.go/New() the check for the optional slash "/" means to check for trailing "/", not for leading "/", and if so, it should use strings.HasSuffix(), not strings.HasPrefix().
Btw.: Nice work here.
Regards, Frank

**Comment by ajvb** [comment]
@FrankRuben haha yeah, thank you.
