### ISSUE TITLE
Add postgres backend support for JobDB

### ISSUE THREAD

**Issue by samdolan** [ajvb/kala#41]
Add a pluggable backend for postgres.

**Comment by alpert** [comment]
Hi. I tried to implement a postgresql jobDB here: https://github.com/alpert/kala/tree/master/job/storage/postgres. I could not implement any tests yet. Will appreciate if you can check and comment. Regards.

**Comment by alpert** [comment]
@ajvb in which branch should I open a pull request? Master?

**Comment by ajvb** [comment]
Closed with #181
