### ISSUE TITLE
Add redis backend support for JobCache

### ISSUE THREAD

**Issue by ajvb** [ajvb/kala#43]
Right now we have a Redis implementation for a JobDB. Would be awesome to have Redis work as the JobCache and/or JobDB.

**Comment by joshualross** [comment]
if this is still an open issue, I could work on it

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by tooolbox** [comment]
@gdhameeja be our guest :)

**Comment by tooolbox** [comment]
In reviewing this further, the JobCache works as a collection of in-memory Jobs which use timers to know when to fire.  Trying to hold the JobCache in something like Redis seems to go against that pattern; the jobs need to be in-memory.

Using Redis as a JobDB is fine, and implemented.
