### ISSUE TITLE
Refactor testing utils into testing package

### ISSUE THREAD

**Issue by samdolan** [ajvb/kala#51]
https://github.com/ajvb/kala/blob/master/api/api_test.go doesn't show up in the coveralls test results, but https://coveralls.io/builds/3291410/source?filename=api%2Ftest_utils.go does. What gives? Should coveralls filter out the test cases themselves? Is it as simple as the `test_*.go` vs. `*_test.go`?

**Comment by ajvb** [comment]
@samdolan What makes you think it isn't picking it up? Check https://coveralls.io/builds/3291410

**Comment by samdolan** [comment]
@ajvb spoke to soon and updated the comment.

**Comment by ajvb** [comment]
@samdolan It's not as easy as expected. #56 accomplishes part of it, but moving stuff from `job/test_utils.go` elsewhere will create circular dep's within the job package having to import the `testing` package.
