### ISSUE TITLE
Work together with dcron?

### ISSUE THREAD

**Issue by falschparker82** [ajvb/kala#58]
Man, how I wish Kala and Dcron would just work together.

https://github.com/ajvb/kala

https://github.com/victorcoder/dcron

Fusing both would be AWESOME (I'd even like to help).

What Dcron gets right:

- Distributed by design

- Raft for the reliable parts, gossip for lightweight sync, a match made in heaven

- Linux mentality

- Dashboard included

- Good docs, nice website, looks serious

What Kala gets right:

- Built much more directly after Chronos, which has an amazing and battle tested API

- Using ISO durations instead of NIHing their own format

- Dependent jobs

**Comment by ajvb** [comment]
@falschparker82 I'm willing to be completely open-minded, but I believe we have different design goals. Kala will be able to be distributed much more like Postgres than etcd. This is so that Kala will work amazing at one node up. Dashboard, better docs, nice website all to come later.
