### ISSUE TITLE
CreateJob takes a map[string]string instead of job.Job?

### ISSUE THREAD

**Issue by elimisteve** [ajvb/kala#78]
Maybe I should be saying this on the Kala Google Group, but I'm looking at https://github.com/ajvb/kala/blob/master/client/client.go#L42-L62 , and https://github.com/ajvb/kala/blob/master/client/client.go#L52 specifically, and wondering why I don't pass in a `job.Job` :-).

Trying to figure out the key names and which ones are required seems unnecessarily challenging to me, but if I could pass in a `job.Job`, then I could look at the definition of `job.Job` to figure that out.

**Comment by ajvb** [comment]
@elimisteve I completely agree. I'll make this change shortly.
