### ISSUE TITLE
Support for synchronous & asynchronous HTTP calls

### ISSUE THREAD

**Issue by falschparker82** [ajvb/kala#96]
Proposal / Request for comments:

We have a mainly API driven stack design and would love to have first-class support for remote jobs in Kala. This would entail changing from a `command` that runs locally on the server to an `endpoint`, that would at execution simply trigger a POST request to the URL specified. 

When working synchronously (recommended for short running jobs only), Kala would listen until the request is closed and look at the HTTP status code for determining errors. When working asynchronously, Kala would provide two endpoints for success and failure. The request would then immediately close with a 200 OK and the requesting API would call back one of the URLs later on.

To distinguish, it would probably be neccessary to introduce a `job_type`, that's then either `local`, `remote_sync` or `remote_async`.

If this is functionality that's needed and the design is solid enough for you guys, we can give it a go ourselves.

**Comment by ajvb** [comment]
Hey @falschparker82,

I love this idea, and your design explanation makes sense to me.

I currently have https://github.com/ajvb/kala/issues/73 open, which is very relevant to this.

Some quick questions about your design:

>When working asynchronously, Kala would provide two endpoints for success and failure.

Why two endpoints and not just one?

>The request would then immediately close with a 200 OK and the requesting API would call back one of the URLs later on.

I like this, but how would you want "later on" to be implemented? Should it happen immediately if the resources are available? (e.g. throw it in a retrying goroutine) Or should it wait a minimum of X seconds?

**Comment by ajvb** [comment]
@falschparker82 Also, what exactly is the `local` `job_type` for?

**Comment by ajvb** [comment]
@falschparker82 Feel free to re-open this, but it's been a while.
